### ISSUE TITLE
org.springframework.social.vkontakte.api.impl.FriendsTemplate transform fails when no fields are specified in the request

### ISSUE THREAD

**Issue by dan-s1** [vkolodrevskiy/spring-social-vkontakte#38]
The VK API specifies for friends.get if the fields parameter is not used a list of user ids are returned.
When I call get(<some user id>, "", -1, -1) I am getting the following stack trace:

java.lang.illegalArgumentException Can not instantiate value of type [simple type, class org.springframework.social.vkontakte.api.VkontakteProfile] from Integral number (<some number>); no single-int-arg constructor/factory/method at [Source: N/A; line: -1. column -1]
at com.fasterxml.jackson.ObjectMapper._convert(ObjectMapper.java:3284)
at com.fasterxml.jackson.ObjectMapper.convertValue(ObjectMapper.java:3210)
at org.springframework.social.vkontakte.api.impl.AbstractVkontakteOperations.deserializeItems(AbstractVkontakteOperations.ja:120)
at org.springframework.social.vkontakte.api.impl.AbstractVkontakteOperations.deserializeVK50ItemsResponse(AbstractVkontakteOperations.ja:114)
at org.springframework.social.vkontakte.api.impl.FriendsTemplate(FriendsTemplate.java:76)

**Comment by dan-s1** [comment]
Sorry I mistyped the call, it should be get(<some id>, "", -1, -1)

**Comment by vkolodrevskiy** [comment]
Since library depends on VK API SDK closing this.
